name: sales_tracking
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.5.6
  provider: ^6.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  template_arb_file: app_en.arb
  output_localization_file: app_localizations.dart
  nullable_getter: false